# Generated by Django 3.2.21 on 2023-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_contactform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
