# Generated by Django 3.2.21 on 2023-09-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_ve6bmd', upload_to='images/')),
                ('resource_url', models.URLField(max_length=100, unique=True)),
                ('country_filter', models.CharField(choices=[('all', 'All'), ('mixed', 'Mixed'), ('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('canary_islands', 'Canary Islands'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costa_rica', 'Costa Rica'), ('cuba', 'Cuba'), ('dominican_republic', 'Dominican Republic'), ('ecuador', 'Ecuador'), ('el_salvador', 'El Salvador'), ('equatorial_guinea', 'Equatorial Guinea'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'), ('panama', 'Panama'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('spain', 'Spain'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela')], default='all', max_length=32)),
                ('resource_type_filter', models.CharField(choices=[('all', 'All'), ('podcast_audio', 'Podcast - Audio'), ('youtube_video', 'YouTube - Video')], default='all', max_length=32)),
                ('difficulty_level_filter', models.CharField(choices=[('all', 'All'), ('easy_native', 'Easy Native'), ('native', 'Native')], default='all', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
