# Generated by Django 3.2.21 on 2023-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='difficulty_level_filter',
            field=models.CharField(choices=[('all', 'All'), ('learner', 'Learner'), ('easy_native', 'Easy Native'), ('native', 'Native')], default='all', max_length=32),
        ),
    ]
