# Generated by Django 3.2.21 on 2023-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_difficulty_level_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type_filter',
            field=models.CharField(choices=[('all', 'All'), ('podcast', 'Podcast - Audio'), ('youtube', 'YouTube - Video')], default='all', max_length=32),
        ),
    ]
