# Generated by Django 3.2.21 on 2023-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20230915_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type_filter',
            field=models.CharField(choices=[('podcast', 'Podcast/Audio'), ('youtube', 'YouTube/Video')], default='all', max_length=32),
        ),
    ]
