# Generated by Django 3.2.21 on 2023-09-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_resource_type_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='desc',
        ),
    ]
