# Generated by Django 3.2.21 on 2023-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_resource_country_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='difficulty_level_filter',
            field=models.CharField(choices=[('learner', 'Learner'), ('Easy Native', 'Easy Native'), ('native', 'Native')], default='all', max_length=32),
        ),
    ]
