# Generated by Django 3.2.21 on 2023-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_alter_resource_difficulty_level_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
