# Generated by Django 3.2.21 on 2023-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_resource_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='country_filter',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('canary_islands', 'Canary Islands'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costa_rica', 'Costa Rica'), ('cuba', 'Cuba'), ('dominican_republic', 'Dominican Republic'), ('ecuador', 'Ecuador'), ('el_salvador', 'El Salvador'), ('equatorial_guinea', 'Equatorial Guinea'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'), ('panama', 'Panama'), ('paraguay', 'Paraguay'), ('puerto_rico', 'Puerto Rico'), ('peru', 'Peru'), ('spain', 'Spain'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela')], max_length=32),
        ),
        migrations.AlterField(
            model_name='resource',
            name='difficulty_level_filter',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('easy_native', 'Easy Native'), ('adv_native', 'Adv Native')], max_length=32),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type_filter',
            field=models.CharField(choices=[('podcast', 'Podcast/Audio'), ('youtube', 'YouTube/Video')], max_length=32),
        ),
    ]
